<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Agenda Clínica | HIS</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.css" rel="stylesheet">
    <style>
        :root { --navy:#102a43; --ink:#243b53; --muted:#627d98; --line:#e5edf3; --mint:#2cb67d; --sky:#3c88c8; --canvas:#f4f8fb; --rose:#dc526a; }
        * { box-sizing:border-box; } body { margin:0; color:var(--ink); background:var(--canvas); font-family:'DM Sans',sans-serif; }
        .topbar { height:72px; padding:0 5.5%; display:flex; align-items:center; justify-content:space-between; background:#fff; border-bottom:1px solid var(--line); }
        .brand { display:flex; align-items:center; gap:12px; color:var(--navy); font-weight:700; letter-spacing:-.3px; } .brand-mark { width:36px;height:36px;display:grid;place-items:center;background:var(--navy);color:#fff;border-radius:11px;font-size:20px; }
        .brand small { display:block; color:var(--muted); font-size:10px; text-transform:uppercase; letter-spacing:1.2px; margin-top:2px; } .user { display:flex;align-items:center;gap:10px;font-size:13px;font-weight:600; } .avatar { width:35px;height:35px;border-radius:50%;background:#dff4eb;color:#16875b;display:grid;place-items:center; }
        .shell { max-width:1440px; margin:0 auto; padding:34px 5.5% 48px; } .eyebrow { color:var(--mint); text-transform:uppercase; font-weight:700; letter-spacing:1.6px; font-size:11px; margin:0 0 7px; } h1 { margin:0; color:var(--navy); font-family:'Playfair Display',serif; font-size:36px; letter-spacing:-1px; } .subtitle { color:var(--muted); margin:8px 0 25px; }
        .overview { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-bottom:22px; }.stat { background:white; padding:17px 19px; border:1px solid var(--line); border-radius:15px; box-shadow:0 6px 18px rgba(26,65,98,.04); }.stat-label{font-size:12px;color:var(--muted);font-weight:600}.stat-value{font-size:25px;font-weight:700;margin-top:6px;color:var(--navy)}.stat-dot{width:9px;height:9px;display:inline-block;border-radius:50%;margin-right:6px}.green{background:var(--mint)}.blue{background:var(--sky)}.red{background:var(--rose)}
        .workspace { background:#fff;border:1px solid var(--line);border-radius:18px;padding:24px;box-shadow:0 14px 30px rgba(26,65,98,.06); }.toolbar { display:flex;align-items:center;justify-content:space-between;margin-bottom:20px; }.legend { display:flex;gap:16px;align-items:center;font-size:12px;color:var(--muted); }.new-btn { border:0;background:var(--navy);color:white;padding:11px 16px;border-radius:9px;font:600 13px 'DM Sans';cursor:pointer;box-shadow:0 6px 13px rgba(16,42,67,.18); }.new-btn:hover{background:#163b5d}
        #calendar { min-height:660px; }.fc { --fc-border-color:var(--line); --fc-page-bg-color:#fff; --fc-today-bg-color:#f0faf6; --fc-button-bg-color:#fff; --fc-button-border-color:var(--line); --fc-button-text-color:var(--ink); --fc-button-hover-bg-color:#f4f8fb; --fc-button-hover-border-color:var(--line); --fc-button-active-bg-color:var(--navy); --fc-button-active-border-color:var(--navy); }.fc .fc-toolbar-title{font:700 19px 'DM Sans';color:var(--navy)}.fc .fc-button{font:600 12px 'DM Sans';padding:7px 11px;text-transform:capitalize;box-shadow:none}.fc-theme-standard td,.fc-theme-standard th{border-color:var(--line)}.fc-col-header-cell-cushion{color:var(--muted);font-size:11px;text-transform:uppercase;padding:12px 4px!important;text-decoration:none}.fc-daygrid-day-number{color:var(--ink);font-size:13px;text-decoration:none;padding:8px!important}.fc-event{border:0;border-radius:6px;padding:3px 5px;font-size:11px;font-weight:600;cursor:pointer}.fc-timegrid-slot-label-cushion{font-size:11px;color:var(--muted)}
        .empty-note { text-align:center;color:var(--muted);font-size:13px;padding:12px;display:none; }.modal { position:fixed;inset:0;background:rgba(16,42,67,.5);display:none;align-items:center;justify-content:center;padding:20px;z-index:10; }.modal.open{display:flex}.modal-card{width:min(520px,100%);background:#fff;border-radius:18px;padding:26px;box-shadow:0 20px 60px rgba(0,0,0,.2)}.modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.modal-head h2{font:700 22px 'Playfair Display';margin:0;color:var(--navy)}.close{border:0;background:#eef4f7;border-radius:50%;width:30px;height:30px;cursor:pointer;color:var(--ink)}
        @media(max-width:700px){.topbar{padding:0 20px}.user span{display:none}.shell{padding:26px 16px}.overview{grid-template-columns:1fr}.workspace{padding:15px}.toolbar{align-items:flex-start;gap:14px}.legend{flex-wrap:wrap;gap:8px}h1{font-size:29px}.fc .fc-toolbar{flex-wrap:wrap;gap:10px}.fc .fc-toolbar-chunk:nth-child(2){order:-1;width:100%;text-align:center}}
    </style>
</head>
<body>
<header class="topbar"><div class="brand"><div class="brand-mark">✚</div><div>HIS Clínica<small>Hospital integrado</small></div></div><div class="user"><span>Recepción general</span><div class="avatar">RG</div></div></header>
<main class="shell">
    <p class="eyebrow">Control de citas</p><h1>Agenda clínica</h1><p class="subtitle">Administra la disponibilidad médica y acompaña cada atención desde un solo lugar.</p>
    <section class="overview"><article class="stat"><div class="stat-label"><i class="stat-dot green"></i>Agendadas hoy</div><div class="stat-value" id="today-count">0</div></article><article class="stat"><div class="stat-label"><i class="stat-dot blue"></i>Esta semana</div><div class="stat-value" id="week-count">0</div></article><article class="stat"><div class="stat-label"><i class="stat-dot red"></i>Canceladas</div><div class="stat-value" id="cancelled-count">0</div></article></section>
    <section class="workspace"><div class="toolbar"><div class="legend"><span><i class="stat-dot green"></i>Agendada</span><span><i class="stat-dot red"></i>Cancelada</span></div><button class="new-btn" id="new-appointment">+ Nueva cita</button></div><div id="calendar"></div><p class="empty-note" id="empty-note">No hay citas en este periodo. Selecciona un horario para crear la primera.</p></section>
</main>
<div class="modal" id="appointment-modal" aria-hidden="true"><div class="modal-card"><div class="modal-head"><h2 id="modal-title">Detalle de cita</h2><button class="close" data-close-modal aria-label="Cerrar">×</button></div><div id="modal-body"></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js"></script>
<script>
const apiUrl = '{{ url('/api/appointments') }}'; const modal=document.getElementById('appointment-modal');
const showModal=(title,html)=>{document.getElementById('modal-title').textContent=title;document.getElementById('modal-body').innerHTML=html;modal.classList.add('open')}; const closeModal=()=>modal.classList.remove('open'); document.querySelector('[data-close-modal]').onclick=closeModal; modal.onclick=e=>{if(e.target===modal)closeModal()};
document.addEventListener('DOMContentLoaded',()=>{const calendar=new FullCalendar.Calendar(document.getElementById('calendar'),{locale:'es',initialView:'timeGridWeek',firstDay:1,height:'auto',nowIndicator:true,slotMinTime:'07:00:00',slotMaxTime:'20:00:00',headerToolbar:{left:'prev,next today',center:'title',right:'dayGridMonth,timeGridWeek,timeGridDay'},events:async(info,success,failure)=>{try{const r=await fetch(`${apiUrl}?start=${info.startStr}&end=${info.endStr}`);if(!r.ok)throw new Error();const rows=await r.json(); updateStats(rows); document.getElementById('empty-note').style.display=rows.length?'none':'block';success(rows.map(a=>({id:a.id,title:`${a.patient_name} · ${a.doctor_name}`,start:a.starts_at,end:a.ends_at,backgroundColor:a.status==='cancelled'?'#dc526a':'#2cb67d',extendedProps:a})));}catch{failure();}},eventClick:info=>{const a=info.event.extendedProps;showModal('Resumen de cita',`<p><strong>${a.patient_name}</strong></p><p>Dr(a). ${a.doctor_name} · ${a.specialty}</p><p style="color:#627d98">La gestión de esta cita se habilitará en el siguiente módulo.</p>`);},selectable:true,select:info=>showModal('Nuevo horario',`<p>Horario seleccionado: <strong>${info.start.toLocaleString('es-GT')}</strong></p><p style="color:#627d98">Usa el botón “Nueva cita” para registrar los datos clínicos.</p>`)});calendar.render();document.getElementById('new-appointment').onclick=()=>showModal('Nueva cita', '<p style="color:#627d98">El formulario de registro se incorporará en la gestión de citas.</p>');});
function updateStats(rows){const now=new Date(),end=new Date(now);end.setDate(now.getDate()+7);document.getElementById('today-count').textContent=rows.filter(x=>new Date(x.starts_at).toDateString()===now.toDateString()&&x.status==='scheduled').length;document.getElementById('week-count').textContent=rows.filter(x=>new Date(x.starts_at)>=now&&new Date(x.starts_at)<=end&&x.status==='scheduled').length;document.getElementById('cancelled-count').textContent=rows.filter(x=>x.status==='cancelled').length;}
</script>
</body>
</html>
